### ISSUE TITLE
Please remove the Debian folder from the repository

### ISSUE THREAD

**Issue by thomasgoirand** [agrover/rtslib-fb#59]
Hi,

I'm the package maintainer for python-rtslib-fb in Debian. I maintain my package using git.debian.org, where all of the packaging is stored. Unfortunately, upstream holding a debian folder is a very bad idea, as it prevents me from merging your latest tags (ie: it create merge conflicts in my Git when I do so).

Could you please remove the debian folder, or at least rename it to something like "debian-upstream", or alternatively, push it to a separate branch (which is perfect for using git-buildpackage, especially if you privde a debian/gbp.conf file)?

Also, I would very much enjoy having contribution within the OpenStack packaging team, to improve the package. The packaging improvements will go to both Debian and Ubuntu (as they sync the package from Debian).

Best would be if you could release a new tag without that debian folder asap, and then I'll be able to package and upload that to Debian Sid.

Thanks in advance.

**Comment by cvubrugier** [comment]
Hi Thomas,

Thank you for packaging python-rtslib-fb in Debian.
I looked at the Debian package and noticed the following patch that changes the path to the configuration file:

    Description: Fix path for the /etc/target/saveconfig.json
     The default path is /etc/target, which IMO is a way too generic. So I changed
     this to /etc/rtslib-fb-target/saveconfig.json
    Author: Thomas Goirand <zigo@debian.org>
    Forwarded: no
    Last-Update: 2014-01-25

I worry that when someone switches from installing rtslib-fb from sources to installing the Debian package, the target configuration will not be restored anymore. I would prefer to have the same configuration file in both cases. Maybe you are right and ```/etc/target/saveconfig.json``` is too generic. I can't think of a better name at the moment though.
