### ISSUE TITLE
'make deb' and 'make rpm' are broken

### ISSUE THREAD

**Issue by agrover** [agrover/rtslib-fb#61]
to fix #59 they were moved. I can't fix them right now, but it would be great if someone did.

**Comment by rlenkala** [comment]
Hi ,

I'm still seeing the same issue while installing rtslib package.Is there any workaround or patch to resolve the error in building the rpm package? 

# make rpm
Exporting the repository files...
Cleaning up the target tree...
Fixing version string...
Generating rpm specfile from template...
Generating rpm changelog...
Generating debian changelog...
Generated release tarball:
    dist/rtslib-fb-2.1.fb59.12.g845606a.tar.gz
Building rpm packages...
error: File /root/new/rtslib-fb/dist/rtslib-2.1.fb59.12.g845606a.tar.gz: No such file or directory
make: *** [build/rpm-stamp] Error 1
# 

Thanks,
Ravindar

**Comment by agrover** [comment]
ok, I pushed a fix for make rpm. make deb is still broken until somebody wants to fix it.

**Comment by rlenkala** [comment]
Thanks Andy for your quick fix. We also see the similar error in compiling "configshell-fb".

 make rpm
Exporting the repository files...
Cleaning up the target tree...
Fixing version string...
Generating rpm specfile from template...
Generating rpm changelog...
Generating debian changelog...
Generated release tarball:
    dist/configshell-fb-1.1.fb19.1.g773dcad.tar.gz
Building rpm packages...
error: File /root/new/configshell-fb/dist/configshell-1.1.fb19.1.g773dcad.tar.gz: No such file or directory
make: *** [build/rpm-stamp] Error 1
[root@Ravindar configshell-fb]#

**Comment by rlenkala** [comment]
Hi Andy,

I have opened one new ticket to track the issue mentioned in my latest comment. If possible, Could you please review the configshell-fb code changes  attached in https://github.com/agrover/configshell-fb/issues/22 and let me know your inputs?

Thanks for your help in Advance!!

Thanks,
Ravindar
