### ISSUE TITLE
Race condition mounting configfs

### ISSUE THREAD

**Issue by colml** [agrover/rtslib-fb#74]
On systems where loading the configfs module (modprobe configfs) automatically mounts /sys/kernel/config, a race condition can occur in the mount_configfs() function in utils.py.

As that function is called immediately after the modprode function, the os.path.ismount check can be called before configfs is finished mounting. The mount command is then run but fails because the mount is busy as it's mounted.

One possible workaround is to make a second os.path.ismount check if the mount command fails, and if it is mounted then we don't raise an exception.
`if process.returncode != 0 and not os.path.ismount("/sys/kernel/config"):`
`raise RTSLibError("Cannot mount configfs")`

I submitted a pull request #73 with this workaround. There are other ways this could be handled as well, this is just one fix that worked for me.

**Comment by agrover** [comment]
PR applied, closing this. Thanks for the report and the fix @colml !
